server:
  error:
    include-message: always
  port: 8085

spring:
  application:
    name: subscriber

  profiles:
    active: default

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: subscriber
          destination: miniprojectjo
          contentType: application/json
        event-out:
          destination: miniprojectjo
          contentType: application/json

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

external:
  subscription:
    url: http://localhost:8085/ # 예시 URL

