apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: subscription
          image: "project20registry.azurecr.io/subscription:v1"
          ports:
            - containerPort: 8085

          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: external.subscription.url
              value: http://localhost:8085

          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8085
            initialDelaySeconds: 90
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8085
            initialDelaySeconds: 240
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 5
