apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: subscriber
          image: "project20registry.azurecr.io/subscriber:v1"
          ports:
            - containerPort: 8085

          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_PROFILES_ACTIVE
              value: docker

          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8085
            initialDelaySeconds: 90
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8085
            initialDelaySeconds: 240
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 5
