apiVersion: v1
kind: Service
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscription
